### ISSUE TITLE
config: Use disambiguated interface names

### ISSUE THREAD

**Issue by efritz** [derision-test/go-mockgen#36]
```yaml
- filename: internal/codeintel/uploads/mocks_test.go
  sources:
    - path: github.com/sourcegraph/sourcegraph/internal/codeintel/uploads/internal/store
      interfaces:
        - Store
    - path: github.com/sourcegraph/sourcegraph/internal/codeintel/uploads/internal/lsifstore
      interfaces:
        - LSIFStore
    - path: github.com/sourcegraph/sourcegraph/internal/codeintel/uploads
      interfaces:
        - GitserverClient
    - path: github.com/sourcegraph/sourcegraph/internal/workerutil/dbworker/store
      interfaces:
        - Store
      prefix: Worker
```

This is currently illegal, although it would generate non-conflicting code. This should be accepted when using non-command-line flags.
